---
driver:
  name: vagrant
  gui: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  environments_path: 'test/environments'
  client_rb:
    environment: 'dev'

verifier:
  name: inspec

platforms:
  - name: ubuntu/xenial64
    driver_config:
      network:
      - ["forwarded_port", {guest: 8081, host: 8081}]
      customize:
        cpus: 2
        memory: 4096

suites:
  - name: nexus
    run_list:
      - recipe[nexus::default]
