name 'nexus'
maintainer 'Ken Erwin'
maintainer_email 'ken@devopslibrary.com'
license 'all_rights'
description 'Installs/Configures nexus'
long_description 'Installs/Configures nexus'
source_url 'https://github.com/devopslibrary/nexus'
issues_url 'https://github..com/devopslibrary/nexus'
version '1.0.0'
chef_version '>= 13'
supports 'linux'
depends 'docker'
